### ISSUE TITLE
Crash with `invalid SecondaryMap key used` when adding an item to a list.

### ISSUE THREAD

**Issue by GaetanLepage** [edfloreshz/cosmic-tasks#11]
[nixpkgs](https://github.com/NixOS/nixpkgs) contributor here.
[I am trying to package `cosmic-tasks`](https://github.com/NixOS/nixpkgs/pull/305008). The application builds and launches fine. However, when I try to add an item to the checklist, it panicks:
```
thread 'main' panicked at src/content.rs:121:40:
invalid SecondaryMap key used
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I re-launch the application, the item appears in the list.

Do you have an idea of what could happen here ?

cc @lilyinstarlight

**Comment by GaetanLepage** [comment]
Note: I am on commit https://github.com/edfloreshz/cosmic-tasks/commit/e6d8539991e5e4ce3d01008442bac0aaa7445201

**Comment by edfloreshz** [comment]
Thanks for the bug report, this is probably due to the recent addition of editable input, I will look into it.
