### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by thatLeaflet** [edfloreshz/cosmic-tasks#7]
As it currently stands, there are no flatpak packages for Cosmic apps and no dedicated runtime for the toolkit.

It would be nice if there was an flatpak package so that people could try out the Cosmic toolkit without using Nix or compiling from source.

**Comment by edfloreshz** [comment]
We have [Flatpak](https://github.com/edfloreshz/cosmic-tasks/blob/main/com.system76.CosmicTasks.yml) 🚀
